package com.hedvig.app

import androidx.lifecycle.MutableLiveData
import com.hedvig.android.owldroid.fragment.KeyGearItemFragment
import com.hedvig.android.owldroid.fragment.KeyGearItemValuationFragment
import com.hedvig.android.owldroid.graphql.KeyGearItemsQuery
import com.hedvig.android.owldroid.type.KeyGearItemCategory
import com.hedvig.app.feature.keygear.ui.tab.KeyGearViewModel

class MockKeyGearViewModel : KeyGearViewModel() {
    override val data = MutableLiveData<KeyGearItemsQuery.Data>()
    override fun sendAutoAddedItems() {}

    init {
        data.postValue(
            KeyGearItemsQuery.Data(
                listOf(
                    KeyGearItemsQuery.KeyGearItem(
                        "KeyGearItem",
                        KeyGearItemsQuery.KeyGearItem.Fragments(
                            KeyGearItemFragment(
                                "KeyGearItem",
                                "123",
                                "Sak",
                                null,
                                listOf(
                                    KeyGearItemFragment.Photo(
                                        "KeyGearItemPhoto",
                                        KeyGearItemFragment.File(
                                            "S3File",
                                            "https://images.unsplash.com/photo-1505156868547-9b49f4df4e04"
                                        )
                                    )
                                ),
                                listOf(),
                                KeyGearItemCategory.PHONE,
                                null,
                                null,
                                KeyGearItemFragment.Deductible(
                                    "MonetaryAmountV2",
                                    "1500.00"
                                ),
                                listOf(),
                                KeyGearItemFragment.MaxInsurableAmount(
                                    "MaxInsurableAmount",
                                    "50000"
                                ),
                                listOf(),
                                false,
                                KeyGearItemFragment.Fragments(
                                    KeyGearItemValuationFragment(
                                        "KeyGearItemValuationFixed",
                                        KeyGearItemValuationFragment.AsKeyGearItemValuationFixed(
                                            "KeyGearItemValuationFixed",
                                            31,
                                            KeyGearItemValuationFragment.Valuation1(
                                                "MonetaryAmountV2",
                                                "1234.00"
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    ),
                    KeyGearItemsQuery.KeyGearItem(
                        "KeyGearItem",
                        KeyGearItemsQuery.KeyGearItem.Fragments(
                            KeyGearItemFragment(
                                "KeyGearItem",
                                "234",
                                "Mackapär",
                                null,
                                listOf(
                                    KeyGearItemFragment.Photo(
                                        "KeyGearItemPhoto",
                                        KeyGearItemFragment.File(
                                            "S3File",
                                            "https://images.unsplash.com/photo-1522199755839-a2bacb67c546"
                                        )
                                    )
                                ),
                                listOf(),
                                KeyGearItemCategory.COMPUTER,
                                null,
                                null,
                                KeyGearItemFragment.Deductible(
                                    "MonetaryAmountV2",
                                    "1500.00"
                                ),
                                listOf(),
                                KeyGearItemFragment.MaxInsurableAmount(
                                    "MaxInsurableAmount",
                                    "50000"
                                ),
                                listOf(),
                                false,
                                KeyGearItemFragment.Fragments(
                                    KeyGearItemValuationFragment(
                                        "KeyGearItemValuationFixed",
                                        KeyGearItemValuationFragment.AsKeyGearItemValuationFixed(
                                            "KeyGearItemValuationFixed",
                                            31,
                                            KeyGearItemValuationFragment.Valuation1(
                                                "MonetaryAmountV2",
                                                "1234.00"
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    ),

                    KeyGearItemsQuery.KeyGearItem(
                        "KeyGearItem",
                        KeyGearItemsQuery.KeyGearItem.Fragments(
                            KeyGearItemFragment(
                                "KeyGearItem",
                                "345",
                                null,
                                null,
                                listOf(),
                                listOf(),
                                KeyGearItemCategory.JEWELRY,
                                null,
                                null,
                                KeyGearItemFragment.Deductible(
                                    "MonetaryAmountV2",
                                    "1500.00"
                                ),
                                listOf(),
                                KeyGearItemFragment.MaxInsurableAmount(
                                    "MaxInsurableAmount",
                                    "50000"
                                ),
                                listOf(),
                                false,
                                KeyGearItemFragment.Fragments(
                                    KeyGearItemValuationFragment(
                                        "KeyGearItemValuationFixed",
                                        KeyGearItemValuationFragment.AsKeyGearItemValuationFixed(
                                            "KeyGearItemValuationFixed",
                                            31,
                                            KeyGearItemValuationFragment.Valuation1(
                                                "MonetaryAmountV2",
                                                "1234.00"
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    )
                )
            )
        )
    }
}
