package com.hedvig.android.core.designsystem.component.tokens

@Suppress("unused")
internal enum class HedvigColorSchemeKeyTokens {
  Background,
  Error,
  ErrorContainer,
  InverseOnSurface,
  InversePrimary,
  InverseSurface,
  OnBackground,
  OnError,
  OnErrorContainer,
  OnPrimary,
  OnPrimaryContainer,
  OnSecondary,
  OnSecondaryContainer,
  OnSurface,
  OnSurfaceVariant,
  OnTertiary,
  OnTertiaryContainer,
  Outline,
  OutlineVariant,
  Primary,
  PrimaryContainer,
  Scrim,
  Secondary,
  SecondaryContainer,
  Surface,
  SurfaceTint,
  SurfaceVariant,
  Tertiary,
  TertiaryContainer,

  WarningContainer,
  OnWarningContainer,
  WarningElement,
  OnWarningElement,
  WarningHighlight,

  TypeElement,
  OnTypeElement,
  LightTypeContainer,
  OnLightTypeContainer,
  TypeContainer,
  OnTypeContainer,
  TypeHighlight,
}
