query GetPayinMethods {
  currentMember {
    paymentMethods(version: 2) {
      chargingDay
      payinMethods {
        ...MemberPaymentMethodFragment
      }
      availableMethods {
        provider
        supportsPayin
        isActive
        details {
          ... on PaymentMethodBankAccountDetails {
            account
            bank
          }
          ... on PaymentMethodSwishDetails {
            phoneNumber
          }
          ... on PaymentMethodInvoiceDetails {
            delivery
            email
          }
        }
      }
    }
  }
}
