@Suppress("DSL_SCOPE_VIOLATION")
plugins {
  id("hedvig.android.library")
  id("hedvig.android.library.compose")
  id("hedvig.android.ktlint")
  id("kotlin-parcelize")
  alias(libs.plugins.serialization)
}

dependencies {
  implementation(projects.app.apollo.core)
  implementation(projects.app.apollo.octopus)
  implementation(projects.app.audioPlayer)
  implementation(projects.app.auth.authAndroid)
  implementation(projects.app.auth.authCore)
  implementation(projects.app.core.coreCommon)
  implementation(projects.app.core.coreCommonAndroid)
  implementation(projects.app.core.coreDesignSystem)
  implementation(projects.app.core.coreResources)
  implementation(projects.app.core.coreUi)
  implementation(projects.app.hanalytics.hanalyticsFeatureFlags)
  implementation(projects.app.hedvigLanguage)
  implementation(projects.app.navigation.navigationActivity)
  implementation(projects.app.navigation.navigationComposeTyped)

  testImplementation(projects.app.core.coreCommonTest)

  implementation(libs.accompanist.navigationAnimation)
  implementation(libs.accompanist.permissions)
  implementation(libs.accompanist.placeholderM3)
  implementation(libs.androidx.compose.foundation)
  implementation(libs.androidx.compose.material)
  implementation(libs.androidx.compose.material3)
  implementation(libs.androidx.compose.material3.windowSizeClass)
  implementation(libs.androidx.compose.materialIconsExtended)
  implementation(libs.androidx.compose.uiCore)
  implementation(libs.androidx.lifecycle.compose)
  implementation(libs.androidx.navigation.common)
  implementation(libs.androidx.navigation.compose)
  implementation(libs.androidx.other.activityCompose)
  implementation(libs.apollo.normalizedCache)
  implementation(libs.arrow.core)
  implementation(libs.coil.coil)
  implementation(libs.coil.compose)
  implementation(libs.datadog.sdk)
  implementation(libs.kiwi.navigationCompose)
  implementation(libs.koin.android)
  implementation(libs.koin.compose)
  implementation(libs.kotlinx.datetime)
  implementation(libs.kotlinx.serialization.core)
  implementation(libs.kotlinx.serialization.json)
  implementation(libs.retrofit)
  implementation(libs.retrofitArrow)
  implementation(libs.retrofitKotlinxSerializationConverter)
  implementation(libs.slimber)

  testImplementation(libs.assertK)
  testImplementation(libs.coroutines.test)
  testImplementation(libs.junit)
  testImplementation(libs.turbine)
}

android {
  namespace = "com.hedvig.android.feature.odyssey"
}
