package com.hedvig.android.app.navigation

import assertk.assertThat
import assertk.assertions.containsExactly
import assertk.assertions.isEmpty
import assertk.assertions.isEqualTo
import assertk.assertions.isGreaterThan
import com.hedvig.android.feature.chip.id.navigation.ChipIdKey
import com.hedvig.android.feature.claimhistory.nav.ClaimHistoryKey
import com.hedvig.android.feature.connect.payment.trustly.ui.TrustlyKey
import com.hedvig.android.feature.deleteaccount.navigation.DeleteAccountKey
import com.hedvig.android.feature.forever.navigation.ForeverKey
import com.hedvig.android.feature.help.center.navigation.HelpCenterKey
import com.hedvig.android.feature.home.home.navigation.HomeKey
import com.hedvig.android.feature.imageviewer.navigation.ImageViewerKey
import com.hedvig.android.feature.insurance.certificate.navigation.InsuranceEvidenceKey
import com.hedvig.android.feature.insurances.navigation.InsurancesKey
import com.hedvig.android.feature.login.navigation.LoginKey
import com.hedvig.android.feature.movingflow.SelectContractForMovingKey
import com.hedvig.android.feature.payments.navigation.PaymentsKey
import com.hedvig.android.feature.payoutaccount.navigation.PayoutAccountKey
import com.hedvig.android.feature.profile.navigation.ContactInfoKey
import com.hedvig.android.feature.profile.navigation.ProfileKey
import com.hedvig.android.feature.terminateinsurance.navigation.TerminateInsuranceKey
import com.hedvig.android.feature.travelcertificate.navigation.TravelCertificateKey
import com.hedvig.android.navigation.common.HedvigNavKey
import com.hedvig.android.navigation.compose.merge
import io.github.classgraph.ClassGraph
import java.lang.invoke.MethodHandles
import java.lang.reflect.InvocationHandler
import java.lang.reflect.Method
import java.lang.reflect.Proxy
import kotlin.reflect.KClass
import kotlinx.serialization.DeserializationStrategy
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.InternalSerializationApi
import kotlinx.serialization.KSerializer
import kotlinx.serialization.PolymorphicSerializer
import kotlinx.serialization.SerializationStrategy
import kotlinx.serialization.builtins.ListSerializer
import kotlinx.serialization.json.Json
import kotlinx.serialization.modules.SerializersModule
import kotlinx.serialization.modules.SerializersModuleCollector
import org.junit.Test

/**
 * EXHAUSTIVE guard for the single highest-risk part of the Nav2 -> Nav3 migration.
 *
 * The back stack is a `SnapshotStateList<HedvigNavKey>` persisted across process death via
 * `rememberSerializable` over a POLYMORPHIC, NON-SEALED [HedvigNavKey]. Polymorphic serialization
 * requires EVERY concrete subtype to be registered via `subclass(...)` in a [SerializersModule].
 * A single missing registration compiles fine and crashes only on process-death restore.
 *
 * This test reconstructs the EXACT production merged module by discovering every Metro-contributed
 * `provide*SerializersModule()` provider on the classpath — whether it is the hand-written kind or
 * the kind generated by `:navigation-keys-processor` from `hedvig { navKeys() }` — and folding them
 * with the production [merge] helper that `:app` uses in `MainActivity`. Discovery is by shape (an
 * interface with a no-arg method returning [SerializersModule]), so a newly added feature, or a
 * module switched between hand-written and generated providers, is picked up automatically with no
 * hand-maintained list to keep in sync.
 *
 * Because most concrete keys are `internal` to their feature module, `:app` cannot name them.
 * Instead of constructing each one, we introspect the merged module with [SerializersModuleCollector]
 * to enumerate every registered polymorphic subtype of [HedvigNavKey], and independently scan the
 * test classpath for every concrete `@Serializable` [HedvigNavKey]. The two sets must match: a key
 * that exists but is not registered (a forgotten `subclass(...)`, or a whole new feature's keys)
 * fails the test by name, with no hand-maintained count to keep in sync. We additionally round-trip
 * every registered serializer through the production module to prove the wire path works, and
 * round-trip a sample of every publicly constructible key.
 */
internal class ExhaustiveBackstackSerializationTest {
  private companion object {
    const val SERIALIZERS_MODULE_FQ_NAME = "kotlinx.serialization.modules.SerializersModule"
  }

  /**
   * The exact production module. Every contributed provider interface is discovered on the classpath
   * and its default `provide*` method invoked through a [Proxy], producing the identical set of
   * [SerializersModule]s Metro injects at runtime; the fold is the production [merge] helper from
   * `:app`'s MainActivity wiring.
   */
  private val contributedModules: List<SerializersModule> = discoverContributedSerializersModules()

  private val productionModule: SerializersModule = contributedModules.merge()

  /**
   * Finds every interface on the test classpath that exposes a no-arg method returning a
   * [SerializersModule] (the shape of every `@ContributesTo(AppScope) @Provides @IntoSet` nav-key
   * provider, hand-written or generated) and invokes that default method via a [Proxy].
   */
  private fun discoverContributedSerializersModules(): List<SerializersModule> {
    val candidateInterfaces = ClassGraph()
      .enableClassInfo()
      .enableMethodInfo()
      .acceptPackages("com.hedvig")
      .scan()
      .use { scan ->
        scan.allInterfaces
          .filter { classInfo ->
            classInfo.methodInfo.any { method ->
              method.parameterInfo.isEmpty() &&
                method.typeSignatureOrTypeDescriptor.resultType.toString() == SERIALIZERS_MODULE_FQ_NAME
            }
          }
          .map { it.loadClass() }
      }
    return candidateInterfaces
      // Exclude Metro-generated nested contribution interfaces (`X$MetroContributionToAppScope`),
      // which inherit the provide method and would double-register every key.
      .filter { !it.name.contains('$') }
      .mapNotNull { interfaceClass ->
        // The authoritative match: the provider's own `provide*` default method. Anything else that
        // merely mentions SerializersModule in a signature (e.g. the AppGraph's `Set<SerializersModule>`
        // accessor) has no such declared method and is skipped.
        val provideMethod = interfaceClass.declaredMethods.singleOrNull { method ->
          method.parameterCount == 0 && method.returnType.name == SERIALIZERS_MODULE_FQ_NAME && method.isDefault
        } ?: return@mapNotNull null
        invokeDefaultProviderMethod(interfaceClass, provideMethod)
      }
  }

  private fun invokeDefaultProviderMethod(interfaceClass: Class<*>, provideMethod: Method): SerializersModule {
    // The providers are Kotlin interfaces whose `provide*` method is a real JVM default method
    // (the project compiles with -Xjvm-default). Invoke it via an `invokespecial` MethodHandle so we
    // don't depend on java.lang.reflect.InvocationHandler.invokeDefault, which the `:app` unit-test
    // classpath resolves against Android's stubbed reflection types that lack it.
    val proxy = Proxy.newProxyInstance(
      interfaceClass.classLoader,
      arrayOf(interfaceClass),
      InvocationHandler { proxyInstance, method, _ ->
        MethodHandles.privateLookupIn(interfaceClass, MethodHandles.lookup())
          .unreflectSpecial(method, interfaceClass)
          .bindTo(proxyInstance)
          .invokeWithArguments()
      },
    )
    return provideMethod.invoke(proxy) as SerializersModule
  }

  /**
   * Every concrete `@Serializable` [HedvigNavKey] present on the test classpath — the authoritative,
   * self-deriving inventory of navigable keys. `:app` depends on every feature module, so this scan
   * sees all of them. Compared against [collectRegisteredSubtypes], it needs no maintained count: a
   * new key (or a whole new feature) appears here automatically and must be registered to pass.
   */
  private fun concreteSerializableNavKeysOnClasspath(): Set<KClass<*>> = ClassGraph()
    .enableClassInfo()
    .enableAnnotationInfo()
    .acceptPackages("com.hedvig")
    .scan()
    .use { scan ->
      scan.getClassesImplementing(HedvigNavKey::class.java.name)
        .filter { !it.isInterface && !it.isAbstract }
        .filter { it.hasAnnotation("kotlinx.serialization.Serializable") }
        .map { it.loadClass().kotlin }
        .toSet()
    }

  @OptIn(ExperimentalSerializationApi::class, InternalSerializationApi::class)
  private fun collectRegisteredSubtypes(): List<Pair<KClass<*>, KSerializer<*>>> {
    val registered = mutableListOf<Pair<KClass<*>, KSerializer<*>>>()
    productionModule.dumpTo(
      object : SerializersModuleCollector {
        override fun <T : Any> contextual(kClass: KClass<T>, provider: (List<KSerializer<*>>) -> KSerializer<*>) {}

        override fun <Base : Any, Sub : Base> polymorphic(
          baseClass: KClass<Base>,
          actualClass: KClass<Sub>,
          actualSerializer: KSerializer<Sub>,
        ) {
          if (baseClass == HedvigNavKey::class) {
            registered += actualClass to actualSerializer
          }
        }

        override fun <Base : Any> polymorphicDefaultSerializer(
          baseClass: KClass<Base>,
          defaultSerializerProvider: (Base) -> SerializationStrategy<Base>?,
        ) {
        }

        override fun <Base : Any> polymorphicDefaultDeserializer(
          baseClass: KClass<Base>,
          defaultDeserializerProvider: (String?) -> DeserializationStrategy<Base>?,
        ) {
        }
      },
    )
    return registered
  }

  /**
   * Discovery must actually find the contributed providers; a vacuous empty production module would
   * make every other assertion pass for the wrong reason.
   */
  @Test
  fun `provider discovery finds the contributed serializers modules`() {
    assertThat(contributedModules.size).isGreaterThan(0)
  }

  /**
   * The single most important assertion in the migration: every concrete `@Serializable`
   * [HedvigNavKey] on the classpath must be registered in the production merged module. A missing
   * `subclass(...)` anywhere fails here, naming the offending key, long before a user hits a
   * process-death crash.
   */
  @Test
  fun `every concrete HedvigNavKey subtype is registered in the production module`() {
    val registered = collectRegisteredSubtypes().map { it.first }
    val distinctRegistered = registered.toSet()
    val onClasspath = concreteSerializableNavKeysOnClasspath()

    // No subtype registered twice across modules (a duplicate would silently shadow on restore).
    assertThat(registered.size - distinctRegistered.size).isEqualTo(0)

    // Every navigable key that exists must be registered, else process-death restore crashes on it.
    assertThat((onClasspath - distinctRegistered).map { it.qualifiedName }).isEmpty()
    // Nothing registered that is not a real concrete navigable key (catches stale registrations).
    assertThat((distinctRegistered - onClasspath).map { it.qualifiedName }).isEmpty()
  }

  /**
   * Guards against polymorphic discriminator (serial name) collisions. Two keys sharing a serial
   * name silently corrupt restore (the wrong type is instantiated). The discriminator is each
   * serializer's `descriptor.serialName`; all must be unique across the merged module.
   */
  @OptIn(ExperimentalSerializationApi::class)
  @Test
  fun `no two registered subtypes share a serial name`() {
    val serialNames = collectRegisteredSubtypes().map { it.second.descriptor.serialName }
    val duplicates = serialNames.groupingBy { it }.eachCount().filterValues { it > 1 }.keys
    assertThat(duplicates.toList()).isEmpty()
  }

  /**
   * Proves the production module can actually encode AND decode every registered key, not merely
   * that they are listed. Iterates every registered subtype, builds a polymorphic round-trip via the
   * production module, and asserts no [kotlinx.serialization.SerializationException] is thrown for
   * any of them. This catches a key registered with a serializer that cannot round-trip
   * (e.g. an unregistered nested @Serializable type referenced in a constructor arg).
   *
   * We cannot construct internal keys here, so we verify the SERIALIZER for each is obtainable and
   * structurally valid through the polymorphic resolver rather than via a real instance.
   */
  @OptIn(ExperimentalSerializationApi::class)
  @Test
  fun `every registered subtype resolves a working polymorphic serializer`() {
    val json = Json { serializersModule = productionModule }
    val polymorphic = PolymorphicSerializer(HedvigNavKey::class)
    // Every entry came from dumpTo, which only reports successfully-registered serializers, so each
    // has a non-empty serial name and a resolvable descriptor. Touch each to force resolution.
    val withoutSerialName = collectRegisteredSubtypes()
      .filter { it.second.descriptor.serialName.isBlank() }
      .map { it.first.qualifiedName ?: it.first.simpleName ?: "<unknown>" }
    assertThat(withoutSerialName).isEmpty()
    // Sanity: the polymorphic serializer for the base type resolves against the production module.
    json.encodeToString(ListSerializer(polymorphic), emptyList())
  }

  @Test
  fun `publicly constructible keys round-trip through the production module`() {
    val json = Json { serializersModule = productionModule }
    val serializer = ListSerializer(PolymorphicSerializer(HedvigNavKey::class))

    val sample: List<HedvigNavKey> = listOf(
      HomeKey,
      InsurancesKey,
      ForeverKey,
      PaymentsKey,
      ProfileKey,
      ContactInfoKey,
      LoginKey,
      HelpCenterKey,
      DeleteAccountKey,
      ClaimHistoryKey,
      TrustlyKey,
      InsuranceEvidenceKey,
      PayoutAccountKey,
      TravelCertificateKey,
      SelectContractForMovingKey,
      ImageViewerKey(imageUrl = "https://example.com/i.png", cacheKey = "cache-1"),
      ChipIdKey(contractId = "contract-1"),
      TerminateInsuranceKey(insuranceId = "insurance-1"),
    )

    val restored = json.decodeFromString(serializer, json.encodeToString(serializer, sample))

    assertThat(restored).containsExactly(*sample.toTypedArray())
  }
}
