name: Update Graphql Schema

on:
  schedule:
    # Run every weekday (Monday-Friday) at 06:00 AM UTC.
    - cron: '0 6 * * 1-5'
  workflow_dispatch:

concurrency:
  group: ref-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  update_gql_schema:
    runs-on: ubuntu-latest-8-vcpu
    steps:
      - uses: ./.github/actions/common-setup
        with:
          gradle-cache-read-only: true
      - name: Update schema
        run: ./gradlew downloadApolloSchemaFromIntrospection
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.ANDROID_REPO_PAT }}
          commit-message: "Update GQL Schema"
          branch: "maintenance/update-schema"
          title: "Maintenance: Update GQL Schema"
          body: ""
