name: Update String resources

on:
  schedule:
    # Run every weekday (Monday-Friday) at 06:00 AM UTC.
    - cron: '0 6 * * 1-5'
  workflow_dispatch:

concurrency:
  group: ref-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  download_strings:
    runs-on: ubuntu-latest-8-vcpu
    steps:
      - uses: actions/checkout@v5
      - name: Setup CI
        uses: ./.github/actions/common-setup
        with:
          download-schema: 'false'
          gradle-cache-read-only: 'false'
          datadog-api-key: ${{ secrets.DATADOG_API_KEY }}
          lokalise-id: ${{ secrets.LOKALISE_ID }}
          lokalise-token: ${{ secrets.LOKALISE_TOKEN }}
      - name: Download strings
        run: ./gradlew downloadStrings
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.ANDROID_REPO_PAT }}
          commit-message: "Download Strings"
          branch: "maintenance/download-strings"
          title: "Maintenance: Download Strings"
          body: ""
